import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  loginView: {
    flex: 1,
    backgroundColor: "#4169E1",
  },
  hdrBlock: {
    position: "relative",
    display: "flex",
    paddingBottom: 20,
    paddingTop: 62,
  },
  loginWave: {
    height: 170,
    resizeMode: "contain",
    position: "absolute",
    top: 0,
    left: -50,
  },
  actions: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 22,
  },
  hdrLabel: {
    fontFamily: "semiBold",
    color: "#fff",
    lineHeight: 22,
    fontSize: 18,
    flex: 1,
  },
  loginContainer: {
    backgroundColor: "#fff",
    flex: 1,
    paddingVertical: 47,
    borderTopLeftRadius: 30,
    borderTopEndRadius: 30,
  },
  meta: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 49,
  },
  title: {
    fontSize: 24,
    color: "#022150",
    letterSpacing: 0.2,
    fontFamily: "semiBold",
    marginBottom: 2,
    lineHeight: 40,
  },
  metaText: {
    fontSize: 14,
    lineHeight: 18,
    fontFamily: "regular",
    color: "#969AA8",
    marginBottom: 29,
  },
  logo: {
    height: 50,
    resizeMode: "contain",
  },
  loginForm: {
    paddingHorizontal: 50,
    marginBottom: 64,
  },
  fieldControl: {
    display: "flex",
  },
  fieldLabel: {
    fontSize: 14,
    color: "#000000",
    fontFamily: "medium",
    lineHeight: 17,
    marginBottom: 10,
  },
  fieldRow: {
    backgroundColor: "#F8F7FB",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "transparent",
    height: 50,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    paddingHorizontal: 18,
  },
  fieldControlTransparent: {
    borderColor: "#4169E1",
    backgroundColor: "transparent",
  },
  fieldLeftIcon: {
    marginRight: 10,
  },
  fieldIconFilled: {
    color: "#4169E1",
  },
  fieldInput: {
    fontFamily: "medium",
    color: "#151624",
    lineHeight: 17,
    fontSize: 14,
    flex: 1,
    height: "100%",
  },
  checked: {
    height: 20,
    width: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#4169E1",
    borderRadius: 50,
  },
  viewPassword: {
    backgroundColor: "#E8F1FF",
    width: 66,
    height: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#4169E1",
    borderRadius: 10,
  },
  viewPasswordText: {
    fontFamily: "medium",
    fontSize: 12,
    color: "#4169E1",
  },
  forgotPassword: {
    display: "flex",
    alignItems: "flex-end",
    marginTop: 12,
  },
  forgotPasswordText: {
    fontFamily: "medium",
    color: "#FE9063",
    lineHeight: 12,
    fontSize: 10,
  },
  signInButton: {
    width: "100%",
    height: 56,
    borderRadius: 15,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#4169E1",
  },
  signInButtonText: {
    fontFamily: "semiBold",
    fontSize: 16,
    color: "#fff",
    lineHeight: 24,
    letterSpacing: 0.02,
  },
  connectOthers: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  connectHdr: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    position: "relative",
  },
  connectBorder: {
    width: "100%",
    height: 1.5,
    backgroundColor: "#F6F6F6",
    position: "absolute",
    top: 12,
  },
  connectText: {
    fontFamily: "medium",
    color: "#969AA8",
    fontSize: 12,
    lineHeight: 20,
    marginBottom: 20,
    backgroundColor: "#fff",
    paddingHorizontal: 8,
  },
  connectActions: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginBottom: 30,
  },
  socialButton: {
    height: 44,
    width: 44,
    backgroundColor: "#F6F6F6",
    borderRadius: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  marginRight0: {
    marginRight: 0,
  },
  noAccountRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  noAccountText: {
    fontFamily: "medium",
    fontSize: 12,
    lineHeight: 16,
    color: "#000000",
  },
  textColor: {
    color: "#FF7A00",
  },
});
